
nc_hc_coalitions <- dplyr::tribble(
	~"coalition", ~"county",
"THPC", "Alexander",
"THPC", "Alleghany",
"THPC", "Ashe",
"THPC", "Caldwell",
"THPC", "Catawba",
"THPC", "Davie",
"THPC", "Davidson",
"THPC", "Forsyth",
"THPC", "Guilford",
"THPC", "Iredell",
"THPC", "Randolph",
"THPC", "Rockingham",
"THPC", "Rowan",
"THPC", "Stokes",
"THPC", "Surry",
"THPC", "Watauga",
"THPC", "Wilkes",
"THPC", "Yadkin",
"MAHPC", "Madison",
"MAHPC", "McDowell",
"MAHPC", "Mitchell",
"MAHPC", "Polk",
"MAHPC", "Rutherford",
"MAHPC", "Swain",
"MAHPC", "Transylvania",
"MAHPC", "Yancey",
"MAHPC", "Avery",
"MAHPC", "Buncombe",
"MAHPC", "Cherokee",
"MAHPC", "Clay",
"MAHPC", "Graham",
"MAHPC", "Haywood",
"MAHPC", "Henderson",
"MAHPC", "Jackson",
"MAHPC", "Macon",
"MHPC", "Burke",
"MHPC","Cleveland",
"MHPC","Catawba",
"MHPC","Lincoln",
"MHPC","Gaston",
"MHPC","Iredell",
"MHPC","Mecklenburg",
"MHPC","Cabarrus",
"MHPC","Union",
"MHPC","Stanly",
"MHPC","Anson",
"MHPC","Richmond",
"MHPC","Scotland",
"DHPC", "Caswell",
"DHPC","Person",
"DHPC","Durham",
"DHPC","Granville",
"DHPC","Vance",
"DHPC","Warren",
"DHPC","Robeson",
"MCRHC", "Alamance",
"MCRHC","Orange",
"MCRHC","Chatham",
"MCRHC","Moore",
"MCRHC","Montgomery",
"MCRHC","Richmond",
"MCRHC","Hoke",
"MCRHC", "Cumberland",
"MCRHC", "Sampson",
"CapRAC","Franklin",
"CapRAC", "Wake",
"CapRAC", "Johnston",
"CapRAC", "Harnett",
"CapRAC", "Lee",
"SHPR", "Bladen",
"SHPR", "Pender",
"SHPR", "Brunswick",
"SHPR", "New Hanover",
"SHPR", "Pender",
"SHPR", "Onslow",
"SHPR", "Duplin",
"EHPC","Beaufort", 
"EHPC","Bertie", 
"EHPC","Camden", 
"EHPC","Carteret", 
"EHPC","Chowan", 
"EHPC","Columbus", 
"EHPC","Craven", 
"EHPC","Currituck", 
"EHPC","Dare", 
"EHPC","Edgecombe", 
"EHPC","Gates", 
"EHPC","Greene", 
"EHPC","Halifax", 
"EHPC","Hertford", 
"EHPC","Hyde", 
"EHPC","Jones", 
"EHPC","Lenoir", 
"EHPC","Martin", 
"EHPC","Nash", 
"EHPC","Northampton", 
"EHPC","Pamlico", 
"EHPC","Pasquotank", 
"EHPC","Perquimans", 
"EHPC","Pitt", 
"EHPC","Tyrrell", 
"EHPC","Washington", 
"EHPC","Wayne", 
"EHPC","Wilson"
)
usethis::use_data(nc_hc_coalitions)
