globalVariables({
	c(
		"cases_daily",
		"cases_confirmed_cum",
		"deaths_daily",
		"deaths_confirmed_cum",
		"patterns",
		"county",
		"Province_State",
		"mobility_file",
		"sub_region_1",
		"sub_region_2",
		"state_name",
		"county_code",
		"value",
		"state",
		".id",
		"state_code",
		"cases",
		"deaths",
		"metric",
		"population",
		"week_of"
	)
})